// Replaces the templated "What does X do?" _Usage:_ Q&A in a card with a
// genuinely tailored one, generated by an actual LLM call (Groq) per
// company — because a script can't tell what's specifically interesting
// about each company, only an intelligence pass over the text can.
//
// This is the "intelligence" step described in the project's audio brief:
// base questions (differentiator / competitors / why now) always exist, but
// which one is worth asking — and the answer — depends on what THIS
// company's own text actually emphasizes, not a fixed template.
//
// Switched from Gemini to Groq (2026-08-31): Gemini's free tier turned out
// to be 20 requests/DAY per project (not per minute as first assumed), and
// the workaround of rotating keys across 3 personal Google accounts runs
// into Google's ToS ban on multi-account quota circumvention plus an active
// abuse-detection crackdown that has been zeroing out flagged accounts'
// quota. Groq's free tier (single account, no card) is 14,400 req/day with
// no such multi-account gray area — see claude-tools/README.md for sources.
//
// Usage: node generate-qa.mjs "Company Name.md" ["Other.md" ...]
//        node generate-qa.mjs --all                 (every file in content/)
//        node generate-qa.mjs --from-file list.txt  (one filename per line —
//                                                     more portable than a
//                                                     shell array across
//                                                     bash/zsh differences)
//
// Reads GROQ_API_KEY from claude-tools/.env. Writes results back into
// content/*.md in place, replacing the existing _Usage:_ section.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, "../..");
const contentDir = path.join(projectRoot, "content");

const envPath = path.join(here, "..", ".env");
const env = Object.fromEntries(
  fs.readFileSync(envPath, "utf8")
    .split("\n")
    .filter(l => l.includes("="))
    .map(l => { const i = l.indexOf("="); return [l.slice(0, i), l.slice(i + 1).trim()]; })
);
const API_KEY = env.GROQ_API_KEY;
if (!API_KEY) { console.error("GROQ_API_KEY not found in claude-tools/.env"); process.exit(1); }
const MODEL = env.GROQ_MODEL || "openai/gpt-oss-120b";

const sleep = ms => new Promise(r => setTimeout(r, ms));
// Groq free tier (single account): 30 req/min, 14,400 req/day per the
// pricepertoken.com / wetheflywheel.com surveys (verify against
// console.groq.com/docs/rate-limits if this ever starts 429ing). 2.5s
// interval keeps us at 24 RPM, comfortably under 30.
const DELAY_MS = 2500;

const args = process.argv.slice(2);
if (!args.length) {
  console.error('usage: node generate-qa.mjs "Company Name.md" [...] | --all | --from-file list.txt');
  process.exit(1);
}
const targets = args[0] === "--all"
  ? fs.readdirSync(contentDir).filter(f => f.endsWith(".md") && f !== "sections.json")
  : args[0] === "--from-file"
  ? fs.readFileSync(args[1], "utf8").split("\n").map(l => l.trim()).filter(Boolean)
  : args;

const PROMPT_INSTRUCTIONS = `You write one "frequently asked" shortcut Q&A for a startup atlas card.

The base questions people ask about any startup are: what's your differentiator,
who are your competitors, why now. But which of those (or something else
entirely) is actually worth asking depends on what THIS company's own text
emphasizes — a short description rarely covers all three, and the interesting
angle differs company to company. Read the text below and pick whichever
single question a sharp reader would actually want answered after reading it
— often a direct comparison to a named competitor or adjacent technology if
one is implied, or a skeptical question about a claim that sounds too good,
or what makes this different from the obvious alternative.

Write the answer the way one engineer explains something to another: direct,
concrete, comfortable using a comparison or analogy, no marketing tone, one
short paragraph. Only use facts present in the text below — do not invent
numbers, competitors, or claims that aren't there.

Respond with ONLY a JSON object: {"question": "...", "answer": "..."}
No markdown fences, no other text.

--- COMPANY TEXT ---
`;

async function generateQA(name, bodyText, retries = 3) {
  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${API_KEY}`,
    },
    body: JSON.stringify({
      model: MODEL,
      messages: [
        { role: "user", content: PROMPT_INSTRUCTIONS + `${name}\n\n${bodyText}` },
      ],
      temperature: 0.4,
      response_format: { type: "json_object" },
    }),
  });
  if (res.status === 429 && retries > 0) {
    const retryAfter = Number(res.headers.get("retry-after"));
    const waitMs = (Number.isFinite(retryAfter) ? retryAfter : 30) * 1000 + 2000;
    console.log(`  (429, waiting ${Math.round(waitMs / 1000)}s before retry)`);
    await sleep(waitMs);
    return generateQA(name, bodyText, retries - 1);
  }
  if (!res.ok) throw new Error(`Groq API ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) throw new Error(`no text in response: ${JSON.stringify(data)}`);
  const cleaned = text.trim().replace(/^```json\s*/i, "").replace(/```$/, "");
  return JSON.parse(cleaned);
}

function stripUsageSection(content) {
  return content.replace(/\n*_Usage:_\n\n"[^"]*"\n\n"[^"]*"\n?$/, "").trimEnd() + "\n";
}

for (let i = 0; i < targets.length; i++) {
  const file = targets[i];
  const filePath = path.join(contentDir, file);
  if (!fs.existsSync(filePath)) { console.warn(`skip (not found): ${file}`); continue; }
  const raw = fs.readFileSync(filePath, "utf8");
  const name = file.replace(/\.md$/, "");
  const bodyForPrompt = raw.replace(/^---\n[\s\S]*?\n---\n/, "").replace(/\n*_Usage:_[\s\S]*$/, "");

  try {
    const { question, answer } = await generateQA(name, bodyForPrompt);
    const withoutOldUsage = stripUsageSection(raw);
    const updated = `${withoutOldUsage}\n_Usage:_\n\n"${question}"\n\n"${answer}"\n`;
    fs.writeFileSync(filePath, updated);
    console.log(`✓ ${file}`);
    console.log(`  Q: ${question}`);
    console.log(`  A: ${answer}\n`);
  } catch (err) {
    console.error(`✗ ${file}: ${err.message}`);
  }

  if (i < targets.length - 1) await sleep(DELAY_MS);
}
